[versions]
agp = "8.1.0"
appcompat = "1.6.1"
kotlin = "1.9.0"
ksp = "1.9.0-1.0.13"
material = "1.9.0"
androidxActivity = "1.7.0"
androidxFragment = "1.6.1"
androidxNavigation = "2.6.0"
androidxLifecycle = "2.2.0"
androidxViewpager2 = "1.0.0"
androidxCardview = "1.0.0"
androidxCoreKtx = "1.10.1"
androidxRoom = "2.5.2"
androidxArchCore = "2.2.0"
androidXStartup = "1.1.1"
coil = "2.2.2"
zxing = "3.2.1"
hilt = "2.45"
moshi = "1.14.0"
coroutines = "1.6.4"
glide = "4.15.1"
baselineProfiles = "1.3.1"
macroBenchmark = "1.2.0-beta03"
uiAutomator = "2.3.0-alpha04"
truth = "1.1.5"
junit = "4.13.2"
turbine = "0.6.0"
robolectric = "4.4"
androidxTest = "1.5.0"
androidxTestJunit = "1.1.5"
androidTestRunner = "1.3.0-beta01"
espresso = "3.5.1"
mockitoKotlin = "2.2.0"
mockitoInline = "3.5.13"
spotless = "6.7.2"
aboutlibraries = "8.9.4"
ktor = "2.3.3"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "androidxNavigation" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
hilt-plugin = { id = "dagger.hilt.android.plugin", version.ref = "hilt" }
mikepenz-aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
zxing = { module = "com.google.zxing:core", version.ref = "zxing" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp = { module = "com.google.devtools.ksp:symbol-processing", version.ref = "ksp" }

material = { module = "com.google.android.material:material", version.ref = "material" }

androidx-navigation-argsPlugin = { group = "androidx.navigation", name = "navigation-safe-args-gradle-plugin", version.ref = "androidxNavigation"}
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidxNavigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidxNavigation" }

mikepenz-aboutlibraries = { module = "com.mikepenz:aboutlibraries", version.ref = "aboutlibraries" }


androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCoreKtx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidxFragment" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "androidxLifecycle" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "androidxViewpager2" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "androidxCardview" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "androidXStartup" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidxRoom" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidxRoom" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidxRoom" }

androidx-arch-core = { module = "androidx.arch.core:core-testing", version.ref = "androidxArchCore" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTest" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestJunit" }
androidx-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }
coil-video = { module = "io.coil-kt:coil-video", version.ref = "coil" }


# unit test
junit = { module = "junit:junit", version.ref = "junit" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
mockito-kotlin  = { module = "com.nhaarman.mockitokotlin2:mockito-kotlin", version.ref = "mockitoKotlin" }
mockito-inline  = { module = "org.mockito:mockito-inline", version.ref = "mockitoInline" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
android-test-runner = { module = "com.android.support.test:runner", version.ref = "androidTestRunner" }
profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "baselineProfiles" }
macrobenchmark = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "macroBenchmark" }
uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiAutomator" }